import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import React, { useState } from "react";
import { useRouter } from "next/router";

const BuildsPage: NextPage = () => {
 const createBuildMutation = api.builds.createBuild.useMutation();
    const builds = api.builds.getBuilds.useQuery();
  const router = useRouter();

  
  return (
    <>
      <Head>
        <title>Submit a Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" gap-4 flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
              <h1>Builds</h1>
              <Link href="/">Home</Link>
              <table>
                  <thead>
                      <tr>
                          <th>Id</th>
                          <th>Match Up</th>
                          <th>Build</th>    
                      </tr>
                  </thead>
                  <tbody>
                      {builds.data?.map(build =>
                          <tr key={build.id}>
                              <td>{build.id}</td>
                              <td>{build.matchup}</td>
                              <td>{build.build}</td>

                          </tr>
                      )}
                    </tbody>
              </table>
     
      </main>
    </>
  );
};


export default BuildsPage;




