import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import React, { useState } from "react";

const Home: NextPage = () => {
 const createBuildMutation = api.builds.createBuild.useMutation();
  
  
  const [buildOrder, setBuildOrder] = useState("");
  const [MatchUp, setMatchUp] = useState("ZvT");

  async function handleSubmitBuildOrder(e: React.FormEvent) {
        e.preventDefault();
        await createBuildMutation.mutateAsync({
            matchup: MatchUp,
            build:buildOrder
          })
        //so that the page doesnt refresh
      }
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" gap-4 flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Welcome to submit Build Order</h1>
        <Link href="/submit-build">Submit  a new Build</Link>
        <Link href="/builds">View Builds</Link>
      </main>
    </>
  );
};
//we want to listen to a user when it types and also update the state when the user types

export default Home;


